language: python
python:
  - "2.7"
env:
  - PGVERSION=9.2
  - CKAN_DATASTORE_POSTGRES_DB=datastore_test
  - CKAN_DATASTORE_POSTGRES_WRITE_USER=ckan_default
  - CKAN_DATASTORE_POSTGRES_READ_USER=datastore_default
  - CKAN_DATASTORE_POSTGRES_READ_PWD=pass
dist: trusty
sudo: required
cache: pip
before_install:
  - chmod +x ./bin/travis-build.bash
  - chmod +x ./bin/travis-run.sh
install: ./bin/travis-build.bash
script:
  - ./bin/travis-run.sh
after_success:
    - coveralls
